config/routes.rb
Rails.application.routes.draw do
  resources :bloks
  resources :lists
  resources :posts
  resources :articles
  devise_for :users
  get 'dashboard/index'
  # root "articles#index"
  root "dashboard#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/d.html.erb
<img src="..." class="rounded me-2" alt="...">

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>
<button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" data-bs-title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>
<button type="button" data-controller="toast" data-action="click->toast#motify" class="btn btn-primary" id="liveToastBtn">Show live toast</button>
<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="liveToast" data-controller="toast" data-action="click->toast#motify" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <strong class="me-auto">Bootstrap</strong>
      <img src="..." class="rounded me-2" alt="...">
      <small>11 mins ago</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      Hello, world! This is a toast message.
    </div>
  </div>
</div>
<hr />

<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item" data-bs-interval="10000">
      <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100"
      width="800" height="400"
      xmlns="http://www.w3.org/2000/svg" role="img"
      aria-label="Placeholder: First slide" preserveAspectRatio="xMidYMid slice"
      focusable="false">
       <title>Placeholder</title>
        <rect width="100%" height="100%" fill="#c5c5f5"></rect>
        <text x="50%" y="50%" fill="#aae" dy=".3em">First slide</text></svg>
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100"
      width="800" height="400"
      xmlns="http://www.w3.org/2000/svg"
      role="img" aria-label="Placeholder: Second slide"
      preserveAspectRatio="xMidYMid slice" focusable="false">
      <title>Placeholder</title>
        <rect width="100%" height="100%" fill="#eea0a0"></rect>
        <text x="50%" y="50%" fill="#d88" dy=".3em">Second slide</text></svg>
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item active">
      <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100"
      width="800" height="400"
      xmlns="http://www.w3.org/2000/svg"
      role="img" aria-label="Placeholder: Third slide"
      preserveAspectRatio="xMidYMid slice" focusable="false">
      <title>Placeholder</title>
        <rect width="100%" height="100%" fill="#b5f5a5"></rect>
        <text x="50%" y="50%" fill="#9c9" dy=".3em">Third slide</text></svg>
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="contaners">
  <hr />
  <%= link_to "New list", new_list_path %> | <%= link_to 'New Blok', new_blok_path %>
  <br />
  <%= link_to "New article", new_article_path %>
  <br />
  <%= link_to "New post", new_post_path %>
</div>