config/routes.rb
Rails.application.routes.draw do
  resources :bloks
  resources :lists
  resources :posts
  resources :articles
  devise_for :users
  get 'dashboard/index'
  # root "articles#index"
  root "dashboard#index"
end

app/models/blok.rb
class Blok < ApplicationRecord
end

app/controllers/bloks_controller.rb
class BloksController < ApplicationController
  before_action :set_blok, only: %i[ show edit update destroy ]

  # GET /bloks or /bloks.json
  def index
    @bloks = Blok.all
  end

  # GET /bloks/1 or /bloks/1.json
  def show
  end

  # GET /bloks/new
  def new
    @blok = Blok.new
  end

  # GET /bloks/1/edit
  def edit
  end

  # POST /bloks or /bloks.json
  def create
    @blok = Blok.new(blok_params)

    respond_to do |format|
      if @blok.save
        format.html { redirect_to blok_url(@blok), notice: "Blok was successfully created." }
        format.json { render :show, status: :created, location: @blok }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blok.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloks/1 or /bloks/1.json
  def update
    respond_to do |format|
      if @blok.update(blok_params)
        format.html { redirect_to blok_url(@blok), notice: "Blok was successfully updated." }
        format.json { render :show, status: :ok, location: @blok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blok.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloks/1 or /bloks/1.json
  def destroy
    @blok.destroy

    respond_to do |format|
      format.html { redirect_to bloks_url, notice: "Blok was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blok
      @blok = Blok.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blok_params
      params.require(:blok).permit(:title, :body)
    end
end

app/helpers/bloks_helper.rb
module BloksHelper
end

app/views/bloks/_blok.html.erb
<div id="<%= dom_id blok %>">
  <p>
    <strong>Title:</strong>
    <%= blok.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blok.body %>
  </p>

</div>

app/views/bloks/_form.html.erb
<%= form_with(model: blok) do |form| %>
  <% if blok.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blok.errors.count, "error") %> prohibited this blok from being saved:</h2>

      <ul>
        <% blok.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bloks/edit.html.erb
<h1>Editing blok</h1>

<%= render "form", blok: @blok %>

<br>

<div>
  <%= link_to "Show this blok", @blok %> |
  <%= link_to "Back to bloks", bloks_path %>
</div>

app/views/bloks/index.html.erb
<div class="container">
  <h1>Blok</h1>
  <%= link_to 'New Blok', new_blok_path %>
  <hr />
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th style="width:10px; heigh:auto"></th>
        <th>Body</th>
        <th style="width:10px; heigh:auto"></th>
        <th colspan="3"></th>
     </tr>
   </thead>
   <tbody>
     <% @bloks.each do |blok| %>
       <tr style="padding:10px 20px 25px 0">
         <td><%= blok.title %></td>
         <td style="width:30px; heigh:auto"></td>
         <td style="padding-top:10px; padding-right:0px; padding-bottom:20px; padding-left:0"><%= truncate(strip_tags(blok.body.to_s), length: 80) %></td>          <td style="width:30px; heigh:auto"></td>
         <td><%= link_to 'Show', blok %></td>
         <td style="width:7px; heigh:auto"></td>
         <td><%= link_to 'Edit', edit_blok_path(blok) %></td>
       </tr>
     <% end %>
    </tbody>
  </table>
</div>
<hr />
<div class="container">
  <%= link_to 'New Blok', new_blok_path %>
</div>

app/views/bloks/index1.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bloks</h1>

<div id="bloks">
  <% @bloks.each do |blok| %>
    <%= render blok %>
    <p>
      <%= link_to "Show this blok", blok %>
    </p>
  <% end %>
</div>

<%= link_to "New blok", new_blok_path %>

app/views/bloks/new.html.erb
<h1>New blok</h1>

<%= render "form", blok: @blok %>

<br>

<div>
  <%= link_to "Back to bloks", bloks_path %>
</div>

app/views/bloks/show.html.erb
<div class="container">
  <h3><%= @blok.title %></h3>
  <div id="navbar" class="1collapse">
    <ul class="nav navbar-nav">
      <li class="">
        <p style="width:400px; heigh:200px">
          <%= @blok.body %>
        </p>
      </li>
    </ul>
  </div>
</div>
<div class="container">
  <%= link_to 'Edit', edit_blok_path(@blok) %> |
  <%= link_to 'Back', bloks_path %>

  <%= button_to "Destroy this blok", @blok, method: :delete %>
</div>

app/views/bloks/show1.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blok %>

<div>
  <%= link_to "Edit this blok", edit_blok_path(@blok) %> |
  <%= link_to "Back to bloks", bloks_path %>

  <%= button_to "Destroy this blok", @blok, method: :delete %>
</div>
<div class="container">
  <h3><%= @blok.title %></h3>
  <div id="navbar" class="1collapse">
    <ul class="nav navbar-nav">
      <li class="">
        <p style="width:400px; heigh:200px">
          <%= @blok.body %>
        </p>
      </li>
    </ul>
  </div>
</div>
<div class="container">
  <%= link_to 'Edit', edit_list_path(@list) %> |
  <%= link_to 'Back', lists_path %>
</div>